### ISSUE TITLE
Definir perfil de usuário

### ISSUE THREAD

**Issue by PedroFMuniz** [Interacao-Humano-Computador/2023.1-DetranGO#34]
# Definir perfil de usuário

## 📝 Descrição

- [x] Criar página para perfil de usuário do site.
- [x] Adicionar página ao GitHub Pages.

## 👩‍💻 Revisor(es)

@phmelosilva

**Comment by amanda-noda** [comment]
Foi realizada a pesquisa dos dias 29-04-2023 até o dia 02-05-2023 e foram resgatadas 54 respostas ao questionário selecionado pelos participantes do grupo
